param(
  [string]$OutputPath = "README.md"
)

$ErrorActionPreference = "Stop"

function Get-RepoRoot {
  return (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

function To-RelativePath {
  param(
    [string]$Root,
    [string]$Path
  )

  $resolvedRoot = (Resolve-Path -LiteralPath $Root).Path
  $resolvedPath = (Resolve-Path -LiteralPath $Path).Path

  if (-not $resolvedRoot.EndsWith([System.IO.Path]::DirectorySeparatorChar)) {
    $resolvedRoot += [System.IO.Path]::DirectorySeparatorChar
  }

  $rootUri = New-Object System.Uri($resolvedRoot)
  $fileUri = New-Object System.Uri($resolvedPath)
  $relativeUri = $rootUri.MakeRelativeUri($fileUri)

  return ([System.Uri]::UnescapeDataString($relativeUri.ToString())).Replace('\', '/')
}

function Get-MetadataValue {
  param(
    [string]$Raw,
    [string]$Key
  )

  $pattern = "(?mi)^\s*\*\s*@${Key}\s+(.*)\s*$"
  $match = [regex]::Match($Raw, $pattern)
  if ($match.Success) {
    return $match.Groups[1].Value.Trim()
  }

  return ""
}

function Escape-TableCell {
  param(
  [string]$Value
  )

  if ([string]::IsNullOrWhiteSpace($Value)) {
    return "-"
  }

  $singleLine = ($Value -replace "\r?\n", " ").Trim()
  return $singleLine.Replace("|", "\|")
}

function Get-LinkPath {
  param(
    [string]$RelativePath
  )

  $segments = $RelativePath -split "/"
  $encoded = foreach ($segment in $segments) {
    [System.Uri]::EscapeDataString($segment)
  }

  return ($encoded -join "/")
}

$repoRoot = Get-RepoRoot
$outputFile = if ([System.IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $repoRoot $OutputPath }

$cssFiles = Get-ChildItem -Path $repoRoot -Recurse -File -Filter "*.css" | Sort-Object FullName
$themes = [System.Collections.Generic.List[object]]::new()

foreach ($file in $cssFiles) {
  $raw = Get-Content -LiteralPath $file.FullName -Raw
  $relativePath = To-RelativePath -Root $repoRoot -Path $file.FullName

  $name = Get-MetadataValue -Raw $raw -Key "name"
  if ([string]::IsNullOrWhiteSpace($name)) {
    $name = $file.BaseName
  }

  $theme = [PSCustomObject]@{
    Name        = $name
    Author      = Get-MetadataValue -Raw $raw -Key "author"
    Version     = Get-MetadataValue -Raw $raw -Key "version"
    Description = Get-MetadataValue -Raw $raw -Key "description"
    Path        = $relativePath
    LinkPath    = Get-LinkPath -RelativePath $relativePath
  }

  $themes.Add($theme)
}

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
$readmeLines = [System.Collections.Generic.List[string]]::new()
$sortedThemes = $themes | Sort-Object Author, Name

$readmeLines.Add("# discord-themes")
$readmeLines.Add("")
$readmeLines.Add("Auto-generated by scripts/generate-readme.ps1 on $timestamp.")
$readmeLines.Add("")
$readmeLines.Add("## Themes")
$readmeLines.Add("")
$readmeLines.Add("| Theme | Author | Version | Description | File |")
$readmeLines.Add("| --- | --- | --- | --- | --- |")

foreach ($theme in $sortedThemes) {
  $themeName = Escape-TableCell -Value $theme.Name
  $themeAuthor = Escape-TableCell -Value $theme.Author
  $themeVersion = Escape-TableCell -Value $theme.Version
  $themeDescription = Escape-TableCell -Value $theme.Description
  $themePath = Escape-TableCell -Value $theme.Path

  $readmeLines.Add("| $themeName | $themeAuthor | $themeVersion | $themeDescription | [$themePath]($($theme.LinkPath)) |")
}

$readmeLines.Add("")
$readmeLines.Add("## Authors")

$authorGroups = $sortedThemes | Group-Object Author

foreach ($group in $authorGroups) {
  $author = if ([string]::IsNullOrWhiteSpace($group.Name)) { "Unknown" } else { $group.Name }
  $readmeLines.Add("")
  $readmeLines.Add("### $author")
  $readmeLines.Add("")
  $readmeLines.Add("| Theme | Version | Description | File |")
  $readmeLines.Add("| --- | --- | --- | --- |")

  $groupThemes = $group.Group | Sort-Object Name
  foreach ($theme in $groupThemes) {
    $themeName = Escape-TableCell -Value $theme.Name
    $themeVersion = Escape-TableCell -Value $theme.Version
    $themeDescription = Escape-TableCell -Value $theme.Description
    $themePath = Escape-TableCell -Value $theme.Path

    $readmeLines.Add("| $themeName | $themeVersion | $themeDescription | [$themePath]($($theme.LinkPath)) |")
  }

  $readmeLines.Add("")
  $readmeLines.Add("Total themes: $($groupThemes.Count)")
}

$readmeLines.Add("")
$readmeLines.Add("## Regenerate")
$readmeLines.Add("")
$readmeLines.Add('```powershell')
$readmeLines.Add('.\generate-readme.cmd')
$readmeLines.Add('```')

$content = ($readmeLines -join [Environment]::NewLine)
Set-Content -LiteralPath $outputFile -Value $content -Encoding utf8

Write-Output "README generated at $outputFile"
Write-Output "CSS files processed: $($themes.Count)"
